plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
cloudinary_cloud_name: circleseven
include:
  - admin
theme: minima
gravatar_hash: c7c96a67607f30615596030dc2c3faf7
author: Administrator
permalink: /:title/
paginate_path: /page/:num/
sass:
  style: compressed
lang: en-GB
markdown: kramdown
description: |-
  Sun Nation is a rock band comprising three members, hailing from Herefordshire and Worcestershire.

  The band's performances feature a blend of original and cover songs from rock, grunge, and pop genres, each played in a unique, adapted rock style that complements the band's setup and instruments. This approach leads to innovative solutions, and challenges the band members to approach each song in a distinctive manner, setting them apart from standard covers bands.
url: https://sun-nation.co.uk
related_posts_count: 4
github_username: mfrench71
cloudinary_base_url: https://res.cloudinary.com/circleseven/image/upload
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: ''
      type: pages
    values:
      layout: page
collections:
  pages:
    output: true
    permalink: /:path/
paginate: 12
title: Sun Nation
timezone: Europe/London
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - scripts/
  - docs/
email: info@sun-nation.co.uk
baseurl: ''
google_fonts:
  enabled: true
  body_font: Roboto Condensed
  heading_font: Impact
  heading_uppercase: true
cloudinary_default_folder: sun-nation
instagram_username: sun_nation
site_image: sn-wall-variation
show_site_description: true
show_site_image: true
